# Generated by Django 3.2.16 on 2023-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicFlexibiity',
            fields=[
                ('acadefx_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_code', models.CharField(max_length=10)),
                ('program_name', models.CharField(max_length=100)),
                ('status_of_implementation_of_cbcss_elective_course_system', models.CharField(db_column='status_of_implementation_of_cbcss/elective_course_system', max_length=100)),
                ('year_of_indroduction', models.CharField(max_length=10)),
                ('link_of_the_relevent_document', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'academic_flexibiity',
                'managed': False,
            },
        ),
    ]
