# Generated by Django 3.2.16 on 2023-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ac',
            fields=[
                ('ac_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_add_on_crtificate_programs_offered', models.CharField(db_column='name_of_add_on/crtificate_programs_offered', max_length=100)),
                ('course_code_if_any_field', models.CharField(db_column='course_code(if_any)', max_length=100)),
                ('year_of_offering', models.CharField(max_length=11)),
                ('duration_of_course', models.CharField(max_length=100)),
                ('number_of_students_enrolled_in_the_year', models.CharField(max_length=11)),
                ('number_of_students_completing_the_course_in_the_year', models.CharField(max_length=11)),
                ('number_of_times_offered_during_the_year', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'ac',
                'managed': False,
            },
        ),
    ]
