# Generated by Django 3.2.16 on 2023-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentNumber1',
            fields=[
                ('p_name', models.IntegerField(primary_key=True, serialize=False)),
                ('programme_name', models.CharField(max_length=100)),
                ('programme_code', models.IntegerField()),
                ('number_of_seats_sanctioned', models.IntegerField()),
                ('number_of_students_admitted', models.IntegerField()),
            ],
            options={
                'db_table': 'enrollment_number1',
                'managed': False,
            },
        ),
    ]
