# Generated by Django 3.2.16 on 2023-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherQuality1',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_full_time_teacher', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('reasearch_guide', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('is_the_teacher_still_serving', models.CharField(max_length=100)),
                ('name_of_the_scholar', models.CharField(max_length=100)),
                ('year_of_registration_of_the_scholar', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'teacher_quality1',
                'managed': False,
            },
        ),
    ]
