# Generated by Django 3.2.16 on 2023-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('workshop_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_the_workshop_seminar', models.CharField(db_column='name_of_the_workshop/seminar', max_length=100)),
                ('number_of_participants', models.IntegerField()),
                ('date_from_to', models.DateTimeField()),
                ('description', models.CharField(max_length=100)),
                ('link_to_the_activity_report_on_the_website', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'workshop',
                'managed': False,
            },
        ),
    ]
