"""
Django settings for naac project.

Generated by 'django-admin startproject' using Django 3.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b$e&y0hxht%#4=x%ww5$o$ct95g6fol_$=%i6=ayfqvs#8c)r#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ac.apps.AcConfig',
    'academic_flexibility.apps.AcademicFlexibilityConfig',
    'activity.apps.ActivityConfig',
    'awards.apps.AwardsConfig',
    'collaborative_activities.apps.CollaborativeActivitiesConfig',
    'curiculam_details.apps.CuriculamDetailsConfig',
    'curiculam_details1.apps.CuriculamDetails1Config',
    'curiculam_details2.apps.CuriculamDetails2Config',
    'enrollnment_number.apps.EnrollnmentNumberConfig',
    'enrollnment_number1.apps.EnrollnmentNumber1Config',
    'extension_programs.apps.ExtensionProgramsConfig',
    'extension_works.apps.ExtensionWorksConfig',
    'login.apps.LoginConfig',
    'mous.apps.MousConfig',
    'teacher_quality1.apps.TeacherQuality1Config',
    'number_of_teachers.apps.NumberOfTeachersConfig',
    'research.apps.ResearchConfig',
    'seat_categories.apps.SeatCategoriesConfig',
    'student_learning.apps.StudentLearningConfig',
    'teaching1.apps.Teaching1Config',
    'teaching_quality.apps.TeachingQualityConfig',
    'workshop.apps.WorkshopConfig',
    'CBCSS.apps.CbcssConfig',
    'circular_aspects.apps.CircularAspectsConfig',
    'academic_flexibility_2.apps.AcademicFlexibility2Config',
    'temp.apps.TempConfig',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'naac.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'naac.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'naac',
        'USER':'root',
        'PASSWORD':'',
        'HOST':'localhost',
        'PORT':'',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
import os
STATIC_URL = '/static/'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR, 'static')

]

MEDIA_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'


import mimetypes
mimetypes.add_type("text/css",".css",True)
mimetypes.add_type("text/css",".js",True)


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
