# Generated by Django 3.2.16 on 2023-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionPrograms',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_activity', models.CharField(max_length=100)),
                ('organisation_unit', models.CharField(max_length=100)),
                ('name_of_the_schema', models.CharField(max_length=100)),
                ('year_of_the_activity', models.CharField(max_length=100)),
                ('number_of_students_participated_in_such_activities', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'extension_programs',
                'managed': False,
            },
        ),
    ]
