# Generated by Django 3.2.16 on 2023-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuriculamDetails',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(db_column='program_Name', max_length=100)),
                ('program_code', models.IntegerField()),
                ('course_details', models.CharField(max_length=100)),
                ('year_of_offering', models.IntegerField()),
                ('student_details', models.CharField(max_length=100)),
                ('name_of_cource', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'curiculam_details',
                'managed': False,
            },
        ),
    ]
