# Generated by Django 3.2.16 on 2023-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mous',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('organisation_with_which_mou_is_signed', models.CharField(max_length=100)),
                ('name_of_the_institution_industry_corporate_house', models.CharField(db_column='name_of_the_institution/industry/corporate_house', max_length=100)),
                ('year_of_mou', models.IntegerField()),
                ('duration', models.CharField(max_length=100)),
                ('list_the_actual_activities_under_each_mou_year_wise', models.CharField(max_length=100)),
                ('number_of_student_teachers_participated_under_mous', models.CharField(db_column='number_of_student/teachers_participated_under_mous', max_length=100)),
            ],
            options={
                'db_table': 'mous',
                'managed': False,
            },
        ),
    ]
