# Generated by Django 3.2.16 on 2023-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeatCategories',
            fields=[
                ('seats_no', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=100)),
                ('sc', models.CharField(max_length=100)),
                ('st', models.CharField(max_length=100)),
                ('obc', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=100)),
                ('gen', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'seat_categories',
                'managed': False,
            },
        ),
    ]
