# Generated by Django 3.2.16 on 2023-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('si_no', models.CharField(max_length=100)),
                ('title_of_the_collaborative_activity', models.CharField(max_length=100)),
                ('name_of_the_collabrating_agency_with_contact_details', models.CharField(max_length=100)),
                ('name_of_the_participant', models.CharField(max_length=100)),
                ('year_of_collaboration', models.IntegerField()),
                ('duration', models.CharField(max_length=100)),
                ('nature_of_the_activity', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'activity',
                'managed': False,
            },
        ),
    ]
