# Generated by Django 3.2.16 on 2023-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfTeachers',
            fields=[
                ('n_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_full_time_teachers', models.CharField(max_length=100)),
                ('pan', models.CharField(db_column='PAN', max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('year_of_appoiment', models.IntegerField()),
                ('number_of_department', models.CharField(max_length=100)),
                ('total_year_of_experience_in_the_same_instituation', models.CharField(max_length=100)),
                ('number_of_appoiment', models.CharField(max_length=100)),
                ('is_the_teacher_still_serving_the_institution', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'number_of_teachers',
                'managed': False,
            },
        ),
    ]
