# Generated by Django 3.2.16 on 2023-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('research_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_the_project_endownments_chairs', models.CharField(db_column='name_of_the_project/endownments,chairs', max_length=100)),
                ('name_of_the_principle_investigator_coinvestigator', models.CharField(db_column='name_of_the_principle_investigator/coinvestigator', max_length=100)),
                ('department_of_principle_investigator', models.CharField(max_length=100)),
                ('amount_sanctioned', models.IntegerField()),
                ('name_of_the_funding_agency', models.CharField(max_length=100)),
                ('type_government_nongovernment_field', models.CharField(db_column='type(government/nongovernment)', max_length=100)),
                ('year_of_award', models.CharField(max_length=100)),
                ('duration_of_project', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'research',
                'managed': False,
            },
        ),
    ]
