# Generated by Django 3.2.16 on 2023-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicFlexibility2',
            fields=[
                ('acadefx2_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=100)),
                ('name_of_teachers_participated', models.CharField(max_length=100)),
                ('name_of_the_body_in_which_full_time_teacher_participated', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'academic_flexibility2',
                'managed': False,
            },
        ),
    ]
